### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by ineiti** [steffahn/transitive_from#1]
Hi,

I'm trying to use the macro in a project with rust 1.58.0. But when I add `transitive_from = "0.1.3"` to my `Cargo.toml`, and then I want to use it as `transitive_from::hierarchy!{...}`, it fails with

```
use of undeclared crate or module `transitive_from`
```

As far as I understand, I don't need to `use transitive_from` or such, correct?

Sorry for the newbie question.

**Comment by steffahn** [comment]
Hmm, I just double-checked and it worked for me in a minimal examle. No, you don’t need to add anything like `use transitive_from;`. If you _try_ to write  `use transitive_from;` anyways, does it give the same error message on the `use` statement? Did you make sure that you saved your `Cargo.toml` after modifying it? If you do `cargo clean` and then `cargo check`, does the cargo output on the terminal give you a `Checking transitive_from v0.1.3` line?

**Comment by ineiti** [comment]
Ouch - I put it under `[dev-dependencies]`, which of course does not work. Sorry for the noise then. With `[dependencies]` it works like a charm, thanks a lot!
